language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=Django==1.9.5
  - DJANGO=Django==1.10.1

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test